repos:
#  - repo: local
#    hooks:
#      - id: jupyter-nb-clear-output
#        name: jupyter-nb-clear-output
#        language: system
#        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: \.ipynb$
        stages: [ pre-commit ]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [ --line-length=100 ]
        name: black
        description: "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi, jupyter]
        additional_dependencies: [".[jupyter]"]

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.10'
    hooks:
      - id: vulture
        args: [
          "--min-confidence", "80",
          "app"  # project_name - path to scan
        ]
        files: ^.*\.py$
        exclude: ^(.git|.venv|venv|build|dist)/.*$

  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-docstrings',
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-simplify',
        ]
        args: [
          "--max-line-length=100",
          "--exclude=.venv,.git,__pycache__,build,dist",
          "--ignore=E203,W503",  # Ignore some style errors that conflict with other tools
        ]
        files: ^app/.*\.py$ # project_name - path to scan

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        files: ^.*\.py$

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
          "--cov=app",  # project_name - path to scan
          "--cov-report=xml",
          "--cov-fail-under=50",
        ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade